name: Maven Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MY_SECRET_1: ${{ secrets.MY_SECRET_1 }}
      MY_SECRET_2: ${{ secrets.MY_SECRET_2 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.9.6'

      - name: Print secrets (for debug, remove in production)
        run: |
          echo "Secret 1: ${MY_SECRET_1}"
          echo "Secret 2: ${MY_SECRET_2}"

      - name: Install dependencies
        run: mvn install -B

